src/Entity/Page.php
<?php

namespace App\Entity;

use App\Repository\PageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: PageRepository::class)]
#[UniqueEntity('Slug')]
class Page
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(length: 5000, nullable: true)]
    private ?string $Content = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $CreationDate = null;

    #[ORM\Column]
    private ?bool $WasEdited = false;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $Slug = null;

    #[ORM\ManyToOne(inversedBy: 'Page')]
    private ?MenuPages $menuPages = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_home = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $robots_settings = null;

    #[ORM\Column(nullable: true)]
    private ?int $parent_id = null;

    #[ORM\Column(length: 255)]
    private ?string $Alias = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(?string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->CreationDate;
    }

    public function setCreationDate(\DateTimeInterface $CreationDate): self
    {
        $this->CreationDate = $CreationDate;

        return $this;
    }

    public function isWasEdited(): ?bool
    {
        return $this->WasEdited;
    }

    public function setWasEdited(bool $WasEdited): self
    {
        $this->WasEdited = $WasEdited;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }

    public function getMenuPages(): ?MenuPages
    {
        return $this->menuPages;
    }

    public function setMenuPages(?MenuPages $menuPages): self
    {
        $this->menuPages = $menuPages;

        return $this;
    }

    public function isIsHome(): ?bool
    {
        return $this->is_home;
    }

    public function setIsHome(?bool $is_home): self
    {
        $this->is_home = $is_home;

        return $this;
    }

    public function getRobotsSettings(): ?string
    {
        return $this->robots_settings;
    }

    public function setRobotsSettings(?string $robots_settings): self
    {
        $this->robots_settings = $robots_settings;

        return $this;
    }

    public function getParentId(): ?int
    {
        return $this->parent_id;
    }

    public function setParentId(?int $parent_id): self
    {
        $this->parent_id = $parent_id;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->Alias;
    }

    public function setAlias(string $Alias): self
    {
        $this->Alias = $Alias;

        return $this;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="{% block description %}{% endblock %}">
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block meta_tags %}
        {% endblock %}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
    {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
            <a class="navbar-brand" href="/">
                <img class="logo-main" src="/img/logo/{{ settings.getSettings.logo }}" alt="logo" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end me-4" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% include '/inc/menu.html.twig' %}
                    <li class="nav-item ms-4">
                        <a class="nav-link" href="/admin">Panel</a>
                    </li>
                    <li class="nav-item ms-4">
                        <a class="nav-link" href="/{{ app.user ? 'logout' : 'login' }}">{{ app.user ? 'Logout' : 'Login' }}</a>
                    </li>
                </ul>
            </div>
        </nav>
    {% endblock %}
        {% block body %}
        {% endblock %}
        <footer class="flex-shrink-0 py-4 bg-dark text-white-50 fixed-bottom">
            <div class="container text-center">
                <small>Copyright &copy; <a class="text-decoration-none text-secondary" href="https://bednarski.xyz">bednarski.xyz</a></small>
            </div>
        </footer>
    </body>
</html>

templates/index.html.twig
{% extends "base.html.twig" %}
{% block title %}
    SEO CMS
{% endblock %}

{% block body %}
    <div>
        <h1 class="p-3">Hello!</h1>
    </div>
{% endblock %}

templates/page.html.twig
{% extends "base.html.twig" %}
{% block title %}
    {{ page.getTitle }}
{% endblock %}
{% block description %}
    {{ page.description }}
{% endblock %}
{% block meta_tags %}
    <meta name="robots" content="{{ page.robotsSettings }}"/>
{% endblock %}
{% block body %}
    <div>
        {% include '/inc/breadcrumbs.html.twig' %}
        <h1 class="p-3">{{ page.name }}</h1>
        <div class="m-3">
            {{ page.content|raw }}
        </div>

    </div>

{% endblock %}